/*
 * machine.js — сборка виртуального хоста Ubuntu 24.04.
 *
 * Машина = VFS + пользователи + процессы + сетевой стек + firewall +
 * systemd + журнал. Часть файлов динамическая (/proc, /sys, /etc/passwd),
 * поэтому `cat /sys/class/net/ens33/mtu` показывает живое значение MTU,
 * а `cat /proc/net/arp` — настоящий neighbour-кэш.
 */
(function (NET) {
  'use strict';

  var U = NET.util;
  var ROOT = { uid: 0, gid: 0, groups: [0], user: 'root' };

  function Machine(spec) {
    spec = spec || {};
    this.name = spec.name || 'host';
    this.hostname = spec.hostname || this.name;
    this.kind = spec.kind || 'host';
    this.shell = spec.shell !== false;
    this.router = !!spec.router;
    this.latency = spec.latency === undefined ? 0.4 : spec.latency;
    this.quirks = spec.quirks || {};
    this.mainUser = spec.user || 'user';
    this.osRelease = spec.osRelease || 'Ubuntu 24.04.1 LTS';
    this.kernel = spec.kernel || '6.8.0-45-generic';

    this.users = NET.UserDB.ubuntu(this.mainUser);
    this.vfs = new NET.VFS(this);
    this.procs = new NET.ProcTable(this);
    this.net = new NET.NetStack(this);
    this.fw = new NET.Firewall(this);
    this.services = new NET.Services(this);
    this.journal = [];
    this.nm = { connections: [] };
    this.resolved = { upstream: [], search: [] };
    this.dns = spec.dns || null;
    this.dhcp = spec.dhcp || null;
    this.http = spec.http || null;
    this.env = {
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      LANG: 'en_US.UTF-8', TERM: 'xterm-256color', SHELL: '/bin/bash'
    };
    this.hwSpec = U.clone(spec.ifaces || []);
    this.specRoutes = U.clone(spec.routes || []);
    this.sysctlSpec = U.clone(spec.sysctl || {});
    this.serviceSpec = spec.services || [];
    this.netplanSpec = spec.netplan || null;
    this.extraFiles = spec.files || {};
    this.sshKeys = spec.sshKeys || [];
    this.packages = spec.packages || null;

    hookSysfs(this);
    buildImage(this);
    this.bootHardware();
    this.defineServices();
    this.bootConfig(true);
  }

  /* ---------- журнал ---------- */

  Machine.prototype.log = function (unit, msg, prio) {
    this.journal.push({ ts: Date.now(), unit: unit || 'kernel', msg: msg, prio: prio || 'info' });
    if (this.journal.length > 1200) this.journal.splice(0, 300);
    NET.bus.emit('machine:log', { machine: this.name, unit: unit, msg: msg, prio: prio });
  };

  /* ---------- resolv.conf ---------- */

  Machine.prototype.setResolvConf = function (servers, search, stub) {
    var lines = [];
    if (stub) {
      lines.push('# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).');
      lines.push('# Do not edit.');
      lines.push('');
    } else {
      lines.push('# Generated by NetworkManager');
    }
    (servers || []).forEach(function (s) { lines.push('nameserver ' + s); });
    if ((search || []).length) lines.push('search ' + search.join(' '));
    lines.push('options edns0 trust-ad');
    NET.errors.attempt('machine.setResolvConf:' + this.name, function () {
      this.vfs.write('/etc/resolv.conf', lines.join('\n') + '\n', ROOT);
    }.bind(this), null, { silent: true, level: 'warn' });
  };

  Machine.prototype.ctxFor = function (userName) {
    return this.users.ctx(userName || this.mainUser);
  };

  /* ---------- железо и загрузка ---------- */

  Machine.prototype.bootHardware = function () {
    var self = this;
    this.net.addIface({ name: 'lo', type: 'loopback', state: 'UP', mtu: 65536 });
    this.net.addAddr('lo', '127.0.0.1/8', { scope: 'host' });
    this.net.addAddr('lo', '::1/128', { scope: 'host' });
    this.hwSpec.forEach(function (i) {
      var iface = self.net.addIface({
        name: i.name, type: i.type || 'ether', mac: i.mac, mtu: i.mtu || 1500,
        segment: i.segment, carrier: i.carrier === undefined ? true : i.carrier,
        link: i.link, vlanId: i.vlanId, state: 'DOWN', managedBy: i.managedBy || 'networkd'
      });
      i.mac = iface.mac;   // фиксируем MAC, чтобы он выжил после reboot
    });
  };

  Machine.prototype.defineServices = function () {
    var self = this;
    var defs = {
      ssh: {
        name: 'ssh', description: 'OpenBSD Secure Shell server',
        exec: '/usr/sbin/sshd -D [listener] 0 of 10-100 startups',
        ports: [{ proto: 'tcp', port: 22 }],
        docs: 'man:sshd(8)\nman:sshd_config(5)',
        preStart: function (m) {
          var conf;
          try { conf = m.vfs.read('/etc/ssh/sshd_config', ROOT); } catch (e) { return 'sshd: no /etc/ssh/sshd_config'; }
          var bad = conf.match(/^\s*(PermitRootLogin|Port)\s*$/m);
          if (bad) return '/etc/ssh/sshd_config line: Missing argument.';
          var m2 = conf.match(/^\s*Port\s+(\S+)/m);
          if (m2 && !/^\d+$/.test(m2[1])) return '/etc/ssh/sshd_config: Badly formatted port number.';
          return null;
        },
        onStart: function (m, u) {
          var conf = '';
          try { conf = m.vfs.read('/etc/ssh/sshd_config', ROOT); } catch (e) {}
          var pm = conf.match(/^\s*Port\s+(\d+)/m);
          var port = pm ? Number(pm[1]) : 22;
          m.net.closeUnitSockets('ssh');
          m.net.listen({ proto: 'tcp', port: port, addr: '0.0.0.0', pid: u.pid, process: 'sshd', unit: 'ssh' });
          u.ports = [{ proto: 'tcp', port: port }];
          m.log('sshd', 'Server listening on 0.0.0.0 port ' + port + '.');
        }
      },
      nginx: {
        name: 'nginx', description: 'A high performance web server and a reverse proxy server',
        exec: '/usr/sbin/nginx -g daemon on; master_process on;',
        ports: [{ proto: 'tcp', port: 80 }, { proto: 'tcp', port: 443 }],
        preStart: function (m) {
          var conf;
          try { conf = m.vfs.read('/etc/nginx/nginx.conf', ROOT); } catch (e) { return 'nginx: [emerg] open() "/etc/nginx/nginx.conf" failed'; }
          if (/\{[^}]*$/.test(conf.replace(/\n/g, ' ')) && (conf.split('{').length !== conf.split('}').length)) {
            return 'nginx: [emerg] unexpected end of file, expecting "}" in /etc/nginx/nginx.conf';
          }
          return null;
        }
      },
      'systemd-networkd': {
        name: 'systemd-networkd', description: 'Network Configuration',
        exec: '/usr/lib/systemd/systemd-networkd', ports: []
      },
      'systemd-resolved': {
        name: 'systemd-resolved', description: 'Network Name Resolution',
        exec: '/usr/lib/systemd/systemd-resolved',
        ports: [{ proto: 'udp', port: 53, addr: '127.0.0.53' }, { proto: 'tcp', port: 53, addr: '127.0.0.53' }]
      },
      NetworkManager: {
        name: 'NetworkManager', description: 'Network Manager',
        exec: '/usr/sbin/NetworkManager --no-daemon', ports: []
      },
      cron: { name: 'cron', description: 'Regular background program processing daemon', exec: '/usr/sbin/cron -f -P', ports: [] },
      ufw: { name: 'ufw', description: 'Uncomplicated firewall', exec: '/lib/ufw/ufw-init', ports: [], type: 'oneshot' },
      named: {
        name: 'named', description: 'BIND Domain Name Server',
        exec: '/usr/sbin/named -f -u bind',
        ports: [{ proto: 'udp', port: 53 }, { proto: 'tcp', port: 53 }]
      },
      'isc-dhcp-server': {
        name: 'isc-dhcp-server', description: 'ISC DHCP IPv4 server',
        exec: '/usr/sbin/dhcpd -f -q -4 -pf /run/dhcp-server/dhcpd.pid',
        ports: [{ proto: 'udp', port: 67 }]
      },
      rsyslog: { name: 'rsyslog', description: 'System Logging Service', exec: '/usr/sbin/rsyslogd -n -iNONE', ports: [] },
      'systemd-journald': { name: 'systemd-journald', description: 'Journal Service', exec: '/usr/lib/systemd/systemd-journald', ports: [], static: true }
    };

    this.procs.spawn({ pid: 1, ppid: 0, cmd: '/sbin/init splash', user: 'root', protected: true });
    (this.serviceSpec || []).forEach(function (s) {
      var name = typeof s === 'string' ? s : s.name;
      var base = defs[name] || { name: name, description: name, exec: '/usr/sbin/' + name, ports: [] };
      var def = {};
      Object.keys(base).forEach(function (k) { def[k] = base[k]; });
      if (typeof s === 'object') {
        Object.keys(s).forEach(function (k) { if (k !== 'name') def[k] = s[k]; });
      }
      def.state = (typeof s === 'object' && s.state) ? s.state : 'active';
      def.enabled = (typeof s === 'object' && s.enabled !== undefined) ? s.enabled : true;
      self.services.define(def);
    });
  };

  /*
   * Применяет постоянную конфигурацию (netplan / NetworkManager) — то же,
   * что делает система при загрузке. Ручные ip-команды здесь не участвуют:
   * именно поэтому забытый netplan apply «теряется» после reboot.
   */
  Machine.prototype.bootConfig = function (initial) {
    var self = this;
    this.sysctlSpec && Object.keys(this.sysctlSpec).forEach(function (k) {
      self.net.sysctl[k] = String(self.sysctlSpec[k]);
    });
    if (this.router) this.net.sysctl['net.ipv4.ip_forward'] = '1';

    /* статические адреса/маршруты узлов инфраструктуры задаются напрямую */
    this.hwSpec.forEach(function (i) {
      (i.addrs || []).forEach(function (a) {
        self.net.addAddr(i.name, a, {});
      });
      if (i.addrs && i.addrs.length) self.net.setLink(i.name, { up: true });
      else if (i.up) self.net.setLink(i.name, { up: true });
    });
    this.specRoutes.forEach(function (r) { self.net.addRoute(r); });

    if (this.netplanSpec && this.services.isActive('systemd-networkd')) {
      var world = NET.world;
      if (world) NET.netcfg.apply(world, this, this.netplanSpec);
    }
    if (this.nm.connections.length && this.services.isActive('NetworkManager')) {
      this.nm.connections.forEach(function (c) {
        if (c.autoconnect !== false) NET.netcfg.nmApply(NET.world, self, c);
      });
    }
    if (initial) {
      this.log('kernel', 'Linux version ' + this.kernel + ' (buildd@lcy02) ');
      this.log('systemd', 'Reached target Network.');
    }
  };

  /* Полная перезагрузка: остаётся только то, что записано в конфигурацию. */
  Machine.prototype.reboot = function () {
    var self = this;
    this.net = new NET.NetStack(this);
    hookSysfs(this);
    /* iptables без persistence: и правила, и политики цепочек сбрасываются */
    this.fw.chains = { INPUT: [], OUTPUT: [], FORWARD: [] };
    this.fw.policy = { INPUT: 'ACCEPT', OUTPUT: 'ACCEPT', FORWARD: 'ACCEPT' };
    this.procs = new NET.ProcTable(this);
    this.journal = [];
    this.bootHardware();
    this.procs.spawn({ pid: 1, ppid: 0, cmd: '/sbin/init splash', user: 'root', protected: true });
    this.services.list().forEach(function (u) {
      u.state = 'inactive'; u.sub = 'dead'; u.pid = null;
    });
    this.services.list().forEach(function (u) {
      if (u.enabled) self.services.start(u.name);
    });
    this.log('systemd', 'Booting Ubuntu ' + this.osRelease);

    /* netplan из файлов — источник истины */
    var loaded = NET.netcfg.loadFiles(this);
    if (this.services.isActive('systemd-networkd') || this.services.isActive('NetworkManager')) {
      if (loaded.doc && loaded.doc.network) NET.netcfg.apply(NET.world, this, loaded.doc);
    }
    this.nm.connections.forEach(function (c) {
      if (c.autoconnect !== false && self.services.isActive('NetworkManager')) {
        NET.netcfg.nmApply(NET.world, self, c);
      }
    });
    this.specRoutes.forEach(function (r) { self.net.addRoute(r); });
    if (this.router) this.net.sysctl['net.ipv4.ip_forward'] = '1';
    NET.bus.emit('machine:reboot', { machine: this.name });
  };

  /* ---------- /sys/class/net ---------- */

  /*
   * Создание интерфейса должно попутно наполнять /sys/class/net.
   * Обёртка ставится один раз: раньше каждый restore() навешивал ещё одну,
   * и после десятка проверок вызовы уходили вглубь на десяток уровней.
   */
  function hookSysfs(m) {
    if (m.net._sysfsHooked) return;
    var origAdd = m.net.addIface.bind(m.net);
    m.net.addIface = function (spec) {
      var iface = origAdd(spec);
      NET.errors.attempt('machine.sysfs:' + m.name, function () { sysfsFor(m, iface); }, null, { silent: true });
      return iface;
    };
    m.net._sysfsHooked = true;
  }

  function sysfsFor(m, iface) {
    var base = '/sys/class/net/' + iface.name;
    m.vfs.mkdir(base, ROOT, { parents: true });
    function dynFile(name, fn) {
      var n = NET.vfsNode('file', 0o444, 0, 0, '');
      n.dyn = fn;
      var parent = m.vfs.get(base, ROOT);
      if (parent) parent.children[name] = n;
    }
    dynFile('mtu', function () { return iface.mtu + '\n'; });
    dynFile('address', function () { return iface.mac + '\n'; });
    dynFile('operstate', function () { return (iface.state === 'UP' ? 'up' : 'down') + '\n'; });
    dynFile('carrier', function () { return (iface.carrier ? '1' : '0') + '\n'; });
    dynFile('ifindex', function () { return iface.index + '\n'; });
    dynFile('flags', function () { return (iface.state === 'UP' ? '0x1003' : '0x1002') + '\n'; });
  }

  /* ---------- образ файловой системы ---------- */

  /*
   * Инфраструктурные узлы (провайдер, публичные серверы, транзитный роутер)
   * не имеют консоли: держать для них полный образ Ubuntu — впустую занятая
   * память при каждой пересборке мира. Им нужен минимум, который читают
   * сервисы: hostname, hosts, resolv.conf, конфиги nginx/sshd и корень сайта.
   */
  function buildImage(m) {
    var v = m.vfs;
    if (!m.shell) return buildMinimalImage(m);
    var dirs = [
      '/bin', '/boot', '/dev', '/etc', '/etc/default', '/etc/netplan', '/etc/network',
      '/etc/ssh', '/etc/ssh/sshd_config.d', '/etc/nginx', '/etc/nginx/sites-available',
      '/etc/nginx/sites-enabled', '/etc/systemd', '/etc/systemd/network', '/etc/systemd/system',
      '/etc/NetworkManager', '/etc/NetworkManager/system-connections', '/etc/apt',
      '/etc/apt/sources.list.d', '/etc/cron.d', '/etc/ufw', '/etc/iptables', '/etc/sysctl.d',
      '/home', '/lib', '/lib/systemd', '/lib/systemd/system', '/media', '/mnt', '/opt',
      '/proc', '/proc/net', '/proc/sys', '/proc/sys/net', '/proc/sys/net/ipv4',
      '/root', '/run', '/run/systemd', '/run/systemd/resolve', '/sbin', '/srv', '/sys',
      '/sys/class', '/sys/class/net', '/tmp', '/usr', '/usr/bin', '/usr/sbin', '/usr/share',
      '/usr/share/doc', '/usr/local', '/usr/local/bin', '/var', '/var/log', '/var/lib',
      '/var/lib/dhcp', '/var/lib/systemd', '/var/spool', '/var/spool/cron',
      '/var/spool/cron/crontabs', '/var/www', '/var/www/html', '/var/tmp'
    ];
    dirs.forEach(function (d) { v.mkdir(d, ROOT, { parents: true, mode: 0o755 }); });
    v.chmod('/tmp', 0o1777, ROOT);
    v.chmod('/root', 0o700, ROOT);

    var home = '/home/' + m.mainUser;
    v.mkdir(home, ROOT, { parents: true, mode: 0o750 });
    var homeNode = v.get(home, ROOT);
    var uctx = m.users.ctx(m.mainUser);
    homeNode.uid = uctx.uid; homeNode.gid = uctx.gid;
    ['Documents', 'scripts', '.ssh'].forEach(function (d) {
      v.mkdir(home + '/' + d, ROOT, { mode: d === '.ssh' ? 0o700 : 0o755 });
      var n = v.get(home + '/' + d, ROOT);
      n.uid = uctx.uid; n.gid = uctx.gid;
    });

    function put(path, content, mode, uid, gid) {
      v.write(path, content, ROOT, { mode: mode === undefined ? 0o644 : mode });
      var n = v.get(path, ROOT);
      if (n) { n.uid = uid || 0; n.gid = gid || 0; }
      return n;
    }

    function dyn(path, fn, mode, uid, gid) {
      var n = put(path, '', mode, uid, gid);
      n.dyn = fn;
      return n;
    }

    /* --- динамические системные файлы --- */
    dyn('/etc/passwd', function (mm) { return mm.users.passwdFile(); }, 0o644);
    dyn('/etc/group', function (mm) { return mm.users.groupFile(); }, 0o644);
    dyn('/etc/shadow', function (mm) { return mm.users.shadowFile(); }, 0o640, 0, 42);
    dyn('/etc/hostname', function (mm) { return mm.hostname + '\n'; }, 0o644);
    dyn('/proc/uptime', function (mm) {
      var up = (Date.now() - mm.procs.bootTime) / 1000;
      return up.toFixed(2) + ' ' + (up * 3.7).toFixed(2) + '\n';
    });
    dyn('/proc/version', function (mm) {
      return 'Linux version ' + mm.kernel + ' (buildd@lcy02-amd64-054) (x86_64-linux-gnu-gcc-13) #45-Ubuntu SMP\n';
    });
    dyn('/proc/loadavg', function (mm) {
      return '0.' + U.randInt(10, 60) + ' 0.' + U.randInt(10, 40) + ' 0.' + U.randInt(5, 30) +
        ' 1/' + (120 + mm.procs.list.length) + ' ' + mm.procs.nextPid + '\n';
    });
    dyn('/proc/meminfo', function () {
      return ['MemTotal:        4022204 kB', 'MemFree:         1830112 kB',
        'MemAvailable:    2914320 kB', 'Buffers:           89204 kB',
        'Cached:           842112 kB', 'SwapTotal:       2097148 kB',
        'SwapFree:        2097148 kB'].join('\n') + '\n';
    });
    dyn('/proc/cpuinfo', function () {
      var out = [];
      for (var i = 0; i < 2; i++) {
        out.push('processor\t: ' + i, 'vendor_id\t: GenuineIntel', 'model name\t: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz',
          'cpu MHz\t\t: 2592.000', 'cache size\t: 12288 KB', '');
      }
      return out.join('\n');
    });
    dyn('/proc/net/dev', function (mm) {
      var lines = ['Inter-|   Receive                                                |  Transmit',
        ' face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed'];
      mm.net.ifaces.forEach(function (i) {
        var s = i.stats;
        lines.push(U.pad(i.name + ':', 7) + U.pad(s.rxBytes, 10) + U.pad(s.rxPackets, 8) +
          '    0    0    0     0          0         0' +
          U.pad(s.txBytes, 10) + U.pad(s.txPackets, 8) + '    0    0    0     0       0          0');
      });
      return lines.join('\n') + '\n';
    });
    dyn('/proc/net/arp', function (mm) {
      var lines = ['IP address       HW type     Flags       HW address            Mask     Device'];
      mm.net.neigh.forEach(function (n) {
        lines.push(U.padRight(n.ip, 17) + '0x1         ' +
          (n.state === 'REACHABLE' || n.state === 'STALE' ? '0x2' : '0x0') + '         ' +
          U.padRight(n.lladdr || '00:00:00:00:00:00', 22) + '*        ' + n.dev);
      });
      return lines.join('\n') + '\n';
    });
    dyn('/proc/sys/net/ipv4/ip_forward', function (mm) {
      return mm.net.sysctl['net.ipv4.ip_forward'] + '\n';
    });
    dyn('/var/log/syslog', function (mm) {
      return mm.journal.map(function (l) {
        return U.syslogTime(l.ts) + ' ' + mm.hostname + ' ' + l.unit + '[' +
          (l.pid || 1) + ']: ' + l.msg;
      }).join('\n') + '\n';
    }, 0o640, 0, 4);
    dyn('/var/log/auth.log', function (mm) {
      return mm.journal.filter(function (l) {
        return l.unit === 'sshd' || l.unit === 'sudo' || l.unit === 'su';
      }).map(function (l) {
        return U.syslogTime(l.ts) + ' ' + mm.hostname + ' ' + l.unit + ': ' + l.msg;
      }).join('\n') + '\n';
    }, 0o640, 0, 4);
    dyn('/var/log/kern.log', function (mm) {
      return mm.journal.filter(function (l) { return l.unit === 'kernel'; }).map(function (l) {
        return U.syslogTime(l.ts) + ' ' + mm.hostname + ' kernel: ' + l.msg;
      }).join('\n') + '\n';
    }, 0o640, 0, 4);

    /* --- статические файлы образа --- */
    put('/etc/os-release', [
      'PRETTY_NAME="' + m.osRelease + '"', 'NAME="Ubuntu"', 'VERSION_ID="24.04"',
      'VERSION="24.04.1 LTS (Noble Numbat)"', 'VERSION_CODENAME=noble', 'ID=ubuntu',
      'ID_LIKE=debian', 'HOME_URL="https://www.ubuntu.com/"', 'UBUNTU_CODENAME=noble'
    ].join('\n') + '\n');

    put('/etc/hosts', [
      '127.0.0.1\tlocalhost',
      '127.0.1.1\t' + m.hostname,
      '',
      '# The following lines are desirable for IPv6 capable hosts',
      '::1     ip6-localhost ip6-loopback',
      'fe00::0 ip6-localnet',
      'ff02::1 ip6-allnodes',
      'ff02::2 ip6-allrouters'
    ].join('\n') + '\n');

    put('/etc/resolv.conf', '# Generated by NetworkManager\nnameserver 127.0.0.53\noptions edns0 trust-ad\n');

    put('/etc/sudoers', [
      'Defaults\tenv_reset',
      'Defaults\tmail_badpass',
      'Defaults\tsecure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"',
      'root\tALL=(ALL:ALL) ALL',
      '%admin ALL=(ALL) ALL',
      '%sudo\tALL=(ALL:ALL) ALL',
      '@includedir /etc/sudoers.d'
    ].join('\n') + '\n', 0o440);

    put('/etc/ssh/sshd_config', [
      '# This is the sshd server system-wide configuration file.',
      'Include /etc/ssh/sshd_config.d/*.conf',
      '',
      'Port 22',
      '#AddressFamily any',
      '#ListenAddress 0.0.0.0',
      '',
      'PermitRootLogin prohibit-password',
      'PubkeyAuthentication yes',
      'AuthorizedKeysFile\t.ssh/authorized_keys',
      'PasswordAuthentication yes',
      'PermitEmptyPasswords no',
      'KbdInteractiveAuthentication no',
      'UsePAM yes',
      'X11Forwarding yes',
      'PrintMotd no',
      'AcceptEnv LANG LC_*',
      'Subsystem\tsftp\t/usr/lib/openssh/sftp-server'
    ].join('\n') + '\n', 0o644);

    put('/etc/nginx/nginx.conf', [
      'user www-data;',
      'worker_processes auto;',
      'pid /run/nginx.pid;',
      'include /etc/nginx/modules-enabled/*.conf;',
      '',
      'events {',
      '        worker_connections 768;',
      '}',
      '',
      'http {',
      '        sendfile on;',
      '        tcp_nopush on;',
      '        types_hash_max_size 2048;',
      '        include /etc/nginx/mime.types;',
      '        default_type application/octet-stream;',
      '        access_log /var/log/nginx/access.log;',
      '        error_log /var/log/nginx/error.log;',
      '        gzip on;',
      '        include /etc/nginx/sites-enabled/*;',
      '}'
    ].join('\n') + '\n');

    put('/etc/nginx/sites-available/default', [
      'server {',
      '        listen 80 default_server;',
      '        listen [::]:80 default_server;',
      '        listen 443 ssl default_server;',
      '        root /var/www/html;',
      '        index index.html;',
      '        server_name _;',
      '        location / {',
      '                try_files $uri $uri/ =404;',
      '        }',
      '}'
    ].join('\n') + '\n');
    v.symlink('/etc/nginx/sites-available/default', '/etc/nginx/sites-enabled/default', ROOT);

    put('/var/www/html/index.html', [
      '<!DOCTYPE html>', '<html><head><title>Welcome to nginx!</title></head>',
      '<body><h1>Welcome to nginx!</h1>',
      '<p>If you see this page, the nginx web server is successfully installed.</p>',
      '</body></html>'
    ].join('\n') + '\n', 0o644, 33, 33);

    put('/etc/sysctl.conf', [
      '# /etc/sysctl.conf - Configuration file for setting system variables',
      '#net.ipv4.ip_forward=1',
      '#net.ipv4.conf.all.rp_filter=1',
      '#net.ipv6.conf.all.disable_ipv6 = 1'
    ].join('\n') + '\n');

    put('/etc/apt/sources.list', [
      'deb http://archive.ubuntu.com/ubuntu noble main restricted universe multiverse',
      'deb http://archive.ubuntu.com/ubuntu noble-updates main restricted universe multiverse',
      'deb http://security.ubuntu.com/ubuntu noble-security main restricted universe multiverse'
    ].join('\n') + '\n');

    put('/etc/default/ufw', [
      'IPV6=yes', 'DEFAULT_INPUT_POLICY="DROP"', 'DEFAULT_OUTPUT_POLICY="ACCEPT"',
      'DEFAULT_FORWARD_POLICY="DROP"', 'MANAGE_BUILTINS=no'
    ].join('\n') + '\n');

    put('/etc/crontab', [
      'SHELL=/bin/sh',
      'PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin',
      '',
      '17 *\t* * *\troot    cd / && run-parts --report /etc/cron.hourly',
      '25 6\t* * *\troot\ttest -x /usr/sbin/anacron || run-parts --report /etc/cron.daily'
    ].join('\n') + '\n');

    put(home + '/.bashrc', [
      '# ~/.bashrc: executed by bash(1) for non-login shells.',
      'case $- in',
      '    *i*) ;;',
      '      *) return;;',
      'esac',
      'HISTSIZE=1000',
      'HISTFILESIZE=2000',
      "alias ll='ls -alF'",
      "alias la='ls -A'",
      "alias l='ls -CF'"
    ].join('\n') + '\n', 0o644, uctx.uid, uctx.gid);

    put(home + '/notes.txt', [
      'Чеклист диагностики (снизу вверх):',
      '1. ip link      — интерфейс UP? есть carrier?',
      '2. ip addr      — адрес и маска верные?',
      '3. ip route     — есть default route? шлюз в своей подсети?',
      '4. ping gw      — L2/L3 до шлюза (ip neigh покажет ARP)',
      '5. ping 8.8.8.8 — маршрутизация наружу',
      '6. dig / resolvectl — имена',
      '7. ss -tulpn / curl — уровень приложения',
      '8. tcpdump      — когда вывод команд противоречив'
    ].join('\n') + '\n', 0o644, uctx.uid, uctx.gid);

    if (m.sshKeys.length) {
      put(home + '/.ssh/authorized_keys', m.sshKeys.join('\n') + '\n', 0o600, uctx.uid, uctx.gid);
    }

    /* netplan из спецификации топологии */
    if (m.netplanSpec) {
      put('/etc/netplan/01-netcfg.yaml',
        '# This file describes the network interfaces available on your system\n' +
        '# For more information, see netplan(5).\n' +
        NET.netcfg.renderYaml(m.netplanSpec) + '\n', 0o600);
    }

    Object.keys(m.extraFiles).forEach(function (p) {
      var spec = m.extraFiles[p];
      if (typeof spec === 'string') put(p, spec);
      else put(p, spec.content, spec.mode, spec.uid, spec.gid);
    });

    /* man-страницы живут отдельно (shell/man.js) — здесь только doc-заглушки */
    put('/usr/share/doc/README', 'Ubuntu ' + m.osRelease + ' documentation stub\n');
  }

  function buildMinimalImage(m) {
    var v = m.vfs;
    ['/etc', '/etc/ssh', '/etc/nginx', '/etc/netplan', '/proc', '/run', '/sys', '/sys/class',
      '/sys/class/net', '/tmp', '/var', '/var/log', '/var/www', '/var/www/html', '/usr', '/usr/sbin'
    ].forEach(function (d) { v.mkdir(d, ROOT, { parents: true, mode: 0o755 }); });

    function put(path, content, mode) {
      v.write(path, content, ROOT, { mode: mode === undefined ? 0o644 : mode });
      return v.get(path, ROOT);
    }

    var hostnameNode = put('/etc/hostname', '');
    hostnameNode.dyn = function (mm) { return mm.hostname + '\n'; };

    put('/etc/os-release', 'PRETTY_NAME="' + m.osRelease + '"\nID=ubuntu\nVERSION_ID="24.04"\n');
    put('/etc/hosts', '127.0.0.1\tlocalhost\n127.0.1.1\t' + m.hostname + '\n');
    put('/etc/resolv.conf', 'nameserver 127.0.0.53\noptions edns0\n');
    put('/etc/ssh/sshd_config', 'Port 22\nPermitRootLogin prohibit-password\nPasswordAuthentication yes\n');
    put('/etc/nginx/nginx.conf', 'user www-data;\nworker_processes auto;\nevents {\n  worker_connections 768;\n}\nhttp {\n  include /etc/nginx/sites-enabled/*;\n}\n');
    put('/var/www/html/index.html', '<!DOCTYPE html>\n<html><body><h1>' + m.hostname + '</h1></body></html>\n');

    var syslog = put('/var/log/syslog', '', 0o640);
    syslog.dyn = function (mm) {
      return mm.journal.map(function (l) {
        return U.syslogTime(l.ts) + ' ' + mm.hostname + ' ' + l.unit + ': ' + l.msg;
      }).join('\n') + '\n';
    };

    Object.keys(m.extraFiles).forEach(function (path) {
      var spec = m.extraFiles[path];
      put(path, typeof spec === 'string' ? spec : spec.content, typeof spec === 'string' ? undefined : spec.mode);
    });
  }

  /* ---------- снапшот ---------- */

  Machine.prototype.snapshot = function () {
    return {
      hostname: this.hostname,
      vfs: this.vfs.snapshot(),
      net: this.net.snapshot(),
      fw: this.fw.snapshot(),
      services: this.services.snapshot(),
      procs: this.procs.snapshot(),
      journal: U.clone(this.journal),
      nm: U.clone(this.nm),
      resolved: U.clone(this.resolved),
      dns: this.dns ? U.clone(this.dns) : null,
      dhcp: this.dhcp ? U.clone(this.dhcp) : null,
      quirks: U.clone(this.quirks),
      sysctl: U.clone(this.net.sysctl),
      env: U.clone(this.env)
    };
  };

  Machine.prototype.restore = function (s) {
    var dynIdx = this.vfs.dynIndex();
    this.hostname = s.hostname;
    this.vfs.restore(s.vfs, dynIdx);
    this.net.restore(s.net);
    hookSysfs(this);
    this.fw.restore(s.fw);
    this.services.restore(s.services);
    this.procs.restore(s.procs);
    this.journal = U.clone(s.journal);
    this.nm = U.clone(s.nm);
    this.resolved = U.clone(s.resolved);
    if (s.dns) this.dns = U.clone(s.dns);
    if (s.dhcp) this.dhcp = U.clone(s.dhcp);
    this.quirks = U.clone(s.quirks);
    this.env = U.clone(s.env);
  };

  NET.Machine = Machine;
  NET.ROOTCTX = ROOT;
})(window.NET);
